const COGNITO_CLIENT_ID = import.meta.env.VITE_COGNITO_CLIENT_ID;
const BASE_URL = import.meta.env.VITE_BASE_API_URL;
const REDIRECT_URL = import.meta.env.VITE_REDIRECT_URL;

export {COGNITO_CLIENT_ID, BASE_URL, REDIRECT_URL};